version: '3.8'

services:
  backend:
    build: .
    command: python app.py
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    user: postgres
    restart: always
    environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - APP_DB_USER=userx
            - APP_DB_PASS=passw
            - APP_DB_NAME=appdb
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
volumes:
  postgres: